#!/bin/csh

set batchdir = ~/batchdirs/$1
cd $batchdir
mkdir -p pbsout

source scriptSource.txt

set h_vmem = $2
set dsFnPath = $3
set DS_JOB = 'sim_job'

echo $DS_JOB $TASK_ID_START-$TASK_ID_END
echo '${dsFnPath}qmatjob_array $batchdir $DS_JOB' '|' qsub -V -hard -l 'h_vmem='$h_vmem -cwd -N $1_$DS_JOB -t $TASK_ID_START-$TASK_ID_END
echo '${dsFnPath}qmatjob_array $batchdir $DS_JOB' | qsub -V -hard -l 'h_vmem='$h_vmem -cwd -N $1_$DS_JOB -t $TASK_ID_START-$TASK_ID_END