Description of ds.xPlt.all2xPlt
ds.xPlt.all2xPlt
PURPOSE
SYNOPSIS
function [xp,is_image] = ds.xPlt.all2xPlt(data)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ds.checkData CHECKDATA - Standardize data structure and auto-populate missing fields
ds.ds2xPlt Convert DynaSim data structure to xp format
ds.img2xPlt Load into DynaSim structure
This function is called by:
ds.merge Merge two Dynasim structures created from different simulations
dsPlot2 % handles=dsPlot(data,'option',value)
SOURCE CODE
function [xp,is_image] = ds.xPlt.all2xPlt(data)
if ~isfield(data,'plot_files')      % Standard DynaSim data structure
    % Check inputs
    data=ds.checkData(data);
      % note: calling ds.checkData() at beginning enables analysis/plotting functions to
      % accept data matrix [time x cells] in addition to DynaSim data structure.
    % Convert input data to xPlt
    xp = ds.ds2xPlt(data);
    is_image = 0;
else                            % Structure of links to plots
    % Convert input data to xPlt
    data_img=data;
    xp = ds.img2xPlt(data_img);
    is_image = 1;
end