Description of displayError
displayError
PURPOSE
DISPLAYERROR - Wrapper to print MATLAB error
SYNOPSIS
function displayError(err)
DESCRIPTION
DISPLAYERROR - Wrapper to print MATLAB error
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ds.simulateModel % data=ds.simulateModel(model,'option',value,...)
ds.studyinfoIO STUDYINFOIO - use lock files to manage concurrent access to a shared studyinfo
ds.updateStudy UPDATESTUDY - helper function to keep track of study metadata when anything is saved
SOURCE CODE
function displayError(err)
%DISPLAYERROR - Wrapper to print MATLAB error
  fprintf('Error: %s\n',err.message);
  for i=1:length(err.stack)
    fprintf('\t in %s (line %g)\n',err.stack(i).name,err.stack(i).line);
  end