Description of ds.merge
ds.merge
PURPOSE
Merge two Dynasim structures created from different simulations
SYNOPSIS
function data_merged = ds.mergeData(data1,data2)
DESCRIPTION
 Merge two Dynasim structures created from different simulations
CROSS-REFERENCE INFORMATION
This function calls:
ds.xPlt.all2xPlt
ds.xPlt.xPlt2ds % data=ds.xPlt.xPlt2ds(obj,varargin)
ds.xPlt.xPlt2dsImage % data=ds.xPlt.xPlt2ds(obj,varargin)
This function is called by:
SOURCE CODE
function data_merged = ds.mergeData(data1,data2)
    % Merge two Dynasim structures created from different simulations
    xp1 = ds.xPlt.all2xPlt(data1);
    xp2 = ds.xPlt.all2xPlt(data2);
    xp_merged = mergeData(xp1,xp2);
    xp_merged.meta = xp1.meta; % Warning - need to make sure metadata merges properly; not yet implemented
    % Sort everything except populations and variables
    inds = true(1,ndims(xp_merged));
    inds(xp_merged.findaxis('populations')) = false;
    inds(xp_merged.findaxis('variables')) = false;
    xp_merged = xp_merged.sortAxis(find(inds));
    if isfield(data1,'plot_files') && isfield(data2,'plot_files')
        data_merged = ds.xPlt.xPlt2dsImage(xp_merged);
    elseif ~isfield(data1,'plot_files') && ~isfield(data2,'plot_files')
        data_merged = ds.xPlt.xPlt2ds(xp_merged);
    else
        error('Unknown input types');
    end
end