Description of ds.options2Keyval
ds.options2Keyval
PURPOSE
OPTIONS2KEYVAL - Convert from options structure to a list of key/value pairs.
SYNOPSIS
function keyval = ds.options2Keyval(options)
DESCRIPTION
OPTIONS2KEYVAL - Convert from options structure to a list of key/value pairs.
 Usage:
   keyvals = ds.options2Keyval(options)
 Inputs:
   - options: options structure to convert
 See also: ds.checkOptions
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ds.checkSolverOptions CHECKSOLVEROPTIONS - standardize simulation options appended to params.mat
ds.getSolveFile GETSOLVEFILE - helper function that creates or retrieves the desired solver file.
ds.importData IMPORTDATA - load data into DynaSim formatted data structure.
ds.plotFR2 PLOTFR2 - plot spike rates in various ways depending on what data was provided.
ds.prepareMEX PREPAREMEX - take an m-file path and compile it using the Matlab coder.
ds.simulateModel % data=ds.simulateModel(model,'option',value,...)
SOURCE CODE
function keyval = ds.options2Keyval(options)
%OPTIONS2KEYVAL - Convert from options structure to a list of key/value pairs.
%
% Usage:
%   keyvals = ds.options2Keyval(options)
%
% Inputs:
%   - options: options structure to convert
%
% See also: ds.checkOptions
% Grab the field names
fields = fieldnames(options);
keyval   = {};
% Loop over the field names, grab the value, and append both to the output
% list of key/value pairs
for i=1:length(fields)
  keyval{end+1} = fields{i};
  keyval{end+1} = options.(fields{i});
end;