Description of ds.selectVariables
ds.selectVariables
PURPOSE
SELECTVARIABLES - determine what variables to plot
SYNOPSIS
function [variables,pop_names]=ds.selectVariables(labels,var_strings)
DESCRIPTION
SELECTVARIABLES - determine what variables to plot
 Usage:
   variables=ds.selectVariables(labels,var_strings)
 Inputs:
   - labels: cell array of variable names
   - var_strings: string or cell array of strings specifying variables to plot
 Outputs:
   - all labels matching specifications in var_strings
 Examples:
   labels={'pop1_v','pop1_iNa_m','pop1_iNa_h','pop2_v','pop2_av','time'};
   var_strings=[];
   var_strings='v';
   var_strings='pop1';
   var_strings='*_v';
   var_strings='pop1_v';
   var_strings='pop1_*';
   var_strings='pop2_*';
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ds.calcACF CALCACF - Calculate the autocorrelation function.
ds.calcCellProperties CALCCELLPROPERTIES - calculates the intrinsic electrophysiological properties of all cells in one or more populations
ds.calcFR CALCFR - Calculate firing rage for DynaSim data
ds.calcFRmulti CALCFRMULTI - extends ds.calcFR to get SUA and MUA firing rates
ds.calcISI CALCISI - Calculate the interspike interval.
ds.calcPower CALCPOWER - Compute spectral analysis of DynaSim data
ds.plotData PLOTDATA - plot data in various ways depending on what data was provided and what options are defined.
ds.plotWaveforms PLOTWAVEFORMS - plot waveforms in various ways depending on what data was provided.
SOURCE CODE
function [variables,pop_names]=ds.selectVariables(labels,var_strings)
%SELECTVARIABLES - determine what variables to plot
%
% Usage:
%   variables=ds.selectVariables(labels,var_strings)
%
% Inputs:
%   - labels: cell array of variable names
%   - var_strings: string or cell array of strings specifying variables to plot
%
% Outputs:
%   - all labels matching specifications in var_strings
%
% Examples:
%   labels={'pop1_v','pop1_iNa_m','pop1_iNa_h','pop2_v','pop2_av','time'};
%   var_strings=[];
%   var_strings='v';
%   var_strings='pop1';
%   var_strings='*_v';
%   var_strings='pop1_v';
%   var_strings='pop1_*';
%   var_strings='pop2_*';
if nargin<2
  var_strings=[];
end
if isempty(var_strings)
  % set default: all pops with state variable of first element of labels
  var=regexp(labels{1},'_.*$','match');
  % add wildcard
  if isempty(var)
    var_strings={'*'};
  else
    var_strings={['*' var{1}]};
  end
elseif ~iscell(var_strings)
  var_strings={var_strings};
end
% loop over cell array of variable indicators
variables={};
for i=1:length(var_strings)
  varstr=var_strings{i};
  % convert state variable into reg string to get variable for all pops
  if ~any(varstr=='*') && any(~cellfun(@isempty,regexp(labels,['_' varstr '$'])))
    varstr=['*_' varstr];
  end
  % convert any population name into reg string to get all variables in pop
  if ~any(varstr=='*') && any(~cellfun(@isempty,regexp(labels,['^' varstr '_'])))
    varstr=[varstr '_*'];
  end
  % add period to get all matches
  varstr=strrep(varstr,'*','.*');
  % find all matches
  matches=regexp(labels,['^' varstr '$'],'match');
  variables=cat(2,variables,matches{:});
end
if nargout>1
  pop_names={};
  for i=1:length(variables)
    name=regexp(variables{i},'^([a-zA-Z0-9]+)_','tokens','once');
    pop_names{end+1}=name{1};
  end
end