#!/bin/csh

cd $1
echo "command = " $2
echo "cwd = " `pwd`
echo "HOSTNAME = " $HOSTNAME
echo "JOB_NAME = " $JOB_ID
echo "JOB_NAME = " $JOB_NAME
#mat -r "$2"
#/usr/local/bin/matlab -nojvm -nosplash -r "$2"
#matlab -nodisplay -singleCompThread -r "$2"
#/usr/local/apps/matlab-2014a/bin/matlab -nojvm -nosplash -r "$2"
/usr/local/apps/matlab-2014a/bin/matlab -nodisplay -singleCompThread -r "$2"
echo "finished"
