#!/bin/csh
#$ -o pbsout/${SGE_TASK_ID}.out
#$ -e pbsout/${SGE_TASK_ID}.err

# $1 is absolute path to working dir
# $2 = 'sim_job', the job name (matlab function name)

cd $1
echo "command = " $2
echo "cwd = " `pwd`
echo "HOSTNAME = " $HOSTNAME
echo "JOB_ID = " $JOB_ID
echo "JOB_NAME = " $JOB_NAME

if (-e pbsout/${SGE_TASK_ID}.out) then
  rm -f pbsout/${SGE_TASK_ID}.out
endif
if (-e pbsout/${SGE_TASK_ID}.err) then
  rm -f pbsout/${SGE_TASK_ID}.err
endif

#/usr/local/apps/matlab-2019a/bin/
module load matlab/2019a
matlab -nodisplay -singleCompThread -r "$2(${SGE_TASK_ID}, ${SGE_TASK_STEPSIZE}, ${SGE_TASK_LAST})" -logfile "logs/$2${SGE_TASK_ID}.log"

echo "finished"