#!/bin/csh

cd $1
echo "ui_command = " $2
echo "m_command = " $3
echo "cwd = " `pwd`
echo "HOSTNAME = " $HOSTNAME
echo "JOB_NAME = " $JOB_ID
echo "JOB_NAME = " $JOB_NAME
# matlab -nodisplay -singleCompThread -r "$3"
# octave-cli --eval "$3"
$2 $3
echo "finished"
