#!/bin/csh

set batchdir = ~/batchdirs/$1
cd $batchdir
mkdir -p pbsout
set joblist = `cat scriptlist.txt`

set ui_command = $2
set l_directives = $3

foreach job ( $joblist )
  echo $job
  if (-e pbsout/$job.out) then
    rm -f pbsout/$job.out
  endif
  if (-e pbsout/$job.err) then
    rm -f pbsout/$job.err
  endif
  # why do we need these two echo instructions? ask jason
  echo "qsub_job $batchdir $ui_command $job" '|' qsub -V -hard -l $l_directives -cwd -N $1_$job -o pbsout/$job.out -e pbsout/$job.err
  echo "qsub_job $batchdir $ui_comman $job" | qsub -V -hard -l $l_directives -cwd -N $1_$job -o pbsout/$job.out -e pbsout/$job.err
  sleep 0.25 #is this the lower limit?
end
